// EDIT ONLY THIS FILE TO PERSONALIZE THE PORTFOLIO.
// Replace placeholder values, links, skills, projects, experience, achievements and resume path.

export type IconName = 'Home' | 'UserRound' | 'Hammer' | 'Building2' | 'ScrollText' | 'Trophy' | 'BookOpen' | 'Mail'

export const portfolio = {
  profile: {
    name: 'Your Name',
    title: 'Developer • AI Enthusiast • Creator',
    shortIntro: 'Building useful digital worlds where thoughtful engineering meets playful ideas.',
    bio: 'I am a curious developer who enjoys turning messy problems into clear, approachable experiences. This space is a living map of what I build, what I learn, and where I want to go next.',
    role: 'Full-Stack Developer',
    level: 28,
    world: 'OVERWORLD / HOME BASE',
    coordinates: 'X: 128 · Y: 64 · Z: -42',
    education: 'Computer Science / Engineering',
    interests: ['AI / ML', 'Web Development', 'Product Design', 'Developer Tools'],
    goals: ['Ship useful products', 'Keep learning in public', 'Build with AI responsibly'],
    email: 'you@example.com',
    github: 'https://github.com/yourusername',
    linkedin: 'https://www.linkedin.com/in/yourusername/',
    resume: '/resume.pdf',
  },
  skills: [
    { name: 'React', icon: 'diamond', level: 90, tone: 'diamond' },
    { name: 'TypeScript', icon: 'book', level: 85, tone: 'enchant' },
    { name: 'JavaScript', icon: 'redstone', level: 88, tone: 'redstone' },
    { name: 'Python', icon: 'emerald', level: 80, tone: 'emerald' },
    { name: 'Git', icon: 'pickaxe', level: 78, tone: 'iron' },
    { name: 'AI / ML', icon: 'command', level: 76, tone: 'purple' },
    { name: 'Node.js', icon: 'slime', level: 82, tone: 'green' },
    { name: 'UI / UX', icon: 'map', level: 74, tone: 'gold' },
  ],
  projects: [
    {
      name: 'FusionNet',
      type: 'MAJOR BUILD',
      description: 'An AI-powered concept focused on bringing multiple signal sources together into one useful workflow.',
      tech: ['React', 'Python', 'AI/ML'],
      challenge: 'Designing a clear product experience around complex model outputs.',
      results: 'Prototype architecture with modular data and model layers.',
      features: ['Unified inputs', 'Model-assisted insights', 'Responsive dashboard'],
      github: 'https://github.com/yourusername/fusionnet',
      demo: 'https://example.com',
    },
    {
      name: 'Campus Quest',
      type: 'SMALL PROJECT',
      description: 'A playful event discovery experience built around quests, progress and lightweight gamification.',
      tech: ['React', 'TypeScript', 'Tailwind'],
      challenge: 'Keeping the gamified layer fun without making navigation harder.',
      results: 'Fast browsing flow with reusable cards and accessible interactions.',
      features: ['Quest cards', 'Event filters', 'Progress tracking'],
      github: 'https://github.com/yourusername/campus-quest',
      demo: 'https://example.com',
    },
    {
      name: 'Signal Forge',
      type: 'EXPERIMENTAL',
      description: 'A technical playground for testing small AI and automation ideas before turning them into products.',
      tech: ['Python', 'APIs', 'Automation'],
      challenge: 'Balancing fast experiments with maintainable boundaries.',
      results: 'Reusable experiment scaffolds and notes for future builds.',
      features: ['Reusable prompts', 'Data transforms', 'Experiment notes'],
      github: 'https://github.com/yourusername/signal-forge',
      demo: 'https://example.com',
    },
  ],
  experience: [
    {
      title: 'Full Stack Development',
      period: '2025 — PRESENT',
      objective: 'Build scalable web applications with strong UX and clean architecture.',
      reward: '+500 XP',
      achievement: '+1 QUEST COMPLETE',
    },
    {
      title: 'AI / ML Exploration',
      period: '2024 — PRESENT',
      objective: 'Prototype practical AI workflows and understand model-driven product design.',
      reward: '+420 XP',
      achievement: '+1 NEW SKILL',
    },
    {
      title: 'Student Builder',
      period: '2022 — PRESENT',
      objective: 'Learn by building, collaborating and shipping increasingly ambitious projects.',
      reward: '+300 XP',
      achievement: '+1 BUILDER BADGE',
    },
  ],
  achievements: [
    { title: 'First Steps', description: 'Started the development journey.', unlocked: true, icon: 'sprout' },
    { title: 'Redstone Engineer', description: 'Built complex technical systems.', unlocked: true, icon: 'cog' },
    { title: 'Diamond Developer', description: 'Completed a major project.', unlocked: true, icon: 'diamond' },
    { title: 'Into the Future', description: 'Exploring AI and emerging technology.', unlocked: false, icon: 'rocket' },
    { title: 'Open Source Wanderer', description: 'Made meaningful contributions in public.', unlocked: false, icon: 'globe' },
    { title: 'Village Leader', description: 'Helped a team turn an idea into a shipped experience.', unlocked: false, icon: 'crown' },
  ],
  nav: [
    { key: 'home', label: 'Home', icon: 'Home' as IconName, keybind: '1' },
    { key: 'about', label: 'About', icon: 'UserRound' as IconName, keybind: '2' },
    { key: 'skills', label: 'Skills', icon: 'Hammer' as IconName, keybind: '3' },
    { key: 'projects', label: 'Projects', icon: 'Building2' as IconName, keybind: '4' },
    { key: 'experience', label: 'Experience', icon: 'ScrollText' as IconName, keybind: '5' },
    { key: 'achievements', label: 'Achievements', icon: 'Trophy' as IconName, keybind: '6' },
    { key: 'resume', label: 'Resume', icon: 'BookOpen' as IconName, keybind: '7' },
    { key: 'contact', label: 'Contact', icon: 'Mail' as IconName, keybind: '8' },
  ],
} as const
